telemetry: false
sonarrEnabled: true
radarrEnabled: false
whisparrEnabled: false
readarrEnabled: false
lidarrEnabled: false

# Sonarr Configuration
sonarr:
  instance1: # Instance name (can be any unique identifier)
    base_url: http://sonarr:8989 # Sonarr instance URL
    # api_key: !secret SONARR_API_KEY # Reference to API key in secrets.yml
    # api_key: !env SONARR_API_KEY # load from environment variable
    api_key: testkeytesttesttesttesttest
    quality_definition:
      type: series # Quality definition type for Sonarr
